alias ..="cd .."
alias ls="ls -G"
alias ll="ls -lAh"

alias gl="git log"
alias gb="git branch"
alias gs="git status"
alias gc="git checkout"
alias ga="git add"
alias gau="git add -u"
alias gd="git diff"
alias gcp="git cherry-pick"
alias gcpc="git cherry-pick --continue"
alias gr="git rebase"
alias gri="git rebase -i"
alias grc="git rebase --continue"
alias gpr="git pull --rebase"
alias gcm="git commit"
alias gcmam="git commit -am"
alias gcmaa="git commit -a --amend"
alias gpsh="git push"
alias gt="git log --all --graph --oneline --decorate"

alias vim="nvim"

alias pb="curl -F c=@- pb"

alias kc="kubectl"

alias refresh="source $HOME/.zshrc"
